### ISSUE TITLE
Deprecation notice: URI.escape is obsolete

### ISSUE THREAD

**Issue by olliebennett** [ideal-postcodes/ideal-postcodes-ruby#9]
I see the following warning in my application;

```
/app/vendor/bundle/ruby/2.7.0/gems/ideal_postcodes-2.0.0/lib/idealpostcodes.rb:70: warning: URI.escape is obsolete
```

A potential replacement for `URI.escape` is outlined [here](https://stackoverflow.com/a/67618304/1323144); most other resources or alternatives seem to behave slightly differently, so that may be the safest approach for compatibility.

**Comment by cblanc** [comment]
@olliebennett could you take a look at 2.0.1

Thanks for reminding

**Comment by olliebennett** [comment]
Great, thanks. `2.0.1` now running in production for us and not causing any issues (and no more deprecation messages). 👌 Appreciate the fast response to my email!
